[stores]

  [stores.minio]
  type = "S3"
  endpoint = "127.0.0.1:9000"
  access-key-id = "1234567890"
  secret-access-key = "abcdefghijklmnopqrstuvwxyz"
  location = "us-east-1"

  [stores.gcs]
  type = "S3"
  version = 2
  endpoint = "https://storage.googleapis.com"
  access-key-id = "helloworld"
  secret-access-key = "very-very-secret-dont-tell-anyone"
  nossl = true
